//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusTimer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class SettingsFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsFile defaultInstance = ((SettingsFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsFile())));
        
        public static SettingsFile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FullPathToMusicFiles {
            get {
                return ((string)(this["FullPathToMusicFiles"]));
            }
            set {
                this["FullPathToMusicFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int StartValue {
            get {
                return ((int)(this["StartValue"]));
            }
            set {
                this["StartValue"] = value;
            }
        }
    }
}
